project_id = "yiudsgcuxbzbtxzbsgra"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:5500"
additional_redirect_urls = [
  "http://localhost:3000",
  "http://127.0.0.1:5500"
]
jwt_expiry = 3600
enable_signup = false

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = true

[storage]
enabled = true
file_size_limit = "10MiB"

[functions.create-staff]
verify_jwt = false

[functions.manage-vsas]
verify_jwt = false