(function () {
  'use strict';
  const esc = (v) => String(v ?? '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;' }[c]));
  async function invoke(body) { const { data, error } = await window.supabaseClient.functions.invoke('manage-vsas', { body }); if (error) throw error; return data; }
  async function manager() { const a = await window.VSASAuth.requireAuth(); if (!a) return null; if (!['admin','hr','manager','ceo'].includes(String(a.profile.role).toLowerCase())) { location.href = 'dashboard.html'; return null; } return a; }
  document.addEventListener('DOMContentLoaded', async () => {
    if (!await manager()) return;
    const list = document.getElementById('departmentList'), form = document.getElementById('departmentForm');
    if (list) { const load = async () => { const { data, error } = await window.supabaseClient.from('departments').select('id,name,description').order('name').limit(100); list.innerHTML = error ? 'Could not load departments.' : (data.length ? data.map((d) => `<p class="notification-item"><strong>${esc(d.name)}</strong><br>${esc(d.description || '')}</p>`).join('') : 'No departments yet.'); }; await load(); form?.addEventListener('submit', async (e) => { e.preventDefault(); try { await invoke({ action: 'department_save', name: document.getElementById('departmentName').value, description: document.getElementById('departmentDescription').value }); form.reset(); load(); } catch (err) { alert(err.message || 'Could not save department.'); } }); }
    const logs = document.getElementById('activityLogList'); if (logs) { const { data, error } = await window.supabaseClient.from('activity_logs').select('action,entity_type,created_at').order('created_at', { ascending: false }).limit(100); logs.innerHTML = error ? 'Could not load activity logs.' : (data.map((x) => `<p class="notification-item"><strong>${esc(x.action)}</strong> · ${esc(x.entity_type)}<br><time>${esc(x.created_at)}</time></p>`).join('') || 'No activity yet.'); }
    const report = document.getElementById('reportForm'); if (report) report.addEventListener('submit', async (e) => { e.preventDefault(); const from = document.getElementById('reportFrom').value, to = document.getElementById('reportTo').value, out = document.getElementById('reportResults'); const { data, error } = await window.supabaseClient.from('attendance').select('work_date,check_in,check_out,profiles!attendance_staff_id_fkey(first_name,last_name,department)').gte('work_date',from).lte('work_date',to).order('work_date', { ascending: false }).limit(500); out.innerHTML = error ? 'Could not run report.' : (data.length ? data.map((r) => `<p class="notification-item"><strong>${esc(r.profiles?.first_name)} ${esc(r.profiles?.last_name)}</strong> · ${esc(r.work_date)} · ${r.check_in ? 'Present' : 'Absent'}</p>`).join('') : 'No attendance records in this range.'); });
  });
})();
